# src/report.py
from __future__ import annotations
from typing import Dict, Any
from datetime import datetime
import pandas as pd
import json
from pathlib import Path


def load_improvements(path: str = "outputs/improvements_latest.json") -> Dict[str, Any]:
    p = Path(path)
    if not p.exists():
        return {}
    return json.loads(p.read_text(encoding="utf-8"))


def generate_markdown_report(
    alignment_csv: str = "outputs/alignment_table.csv",
    improvements_json: str = "outputs/improvements_latest.json",
    out_path: str | None = None,
    top_n_weak: int = 5
) -> str:
    df = pd.read_csv(alignment_csv)
    improvements = load_improvements(improvements_json)

    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    total = len(df)

    # label summary
    label_counts = df["label"].value_counts(dropna=False).to_dict()

    # weak strategies (lowest boosted)
    weak_df = df[df["label"].astype(str).str.lower().eq("weak")].copy()
    if "best_boosted_similarity" in weak_df.columns:
        weak_df = weak_df.sort_values("best_boosted_similarity", ascending=True)

    weak_top = weak_df.head(top_n_weak)

    lines = []
    lines.append(f"# ISPS – Strategy–Action Alignment Report\n")
    lines.append(f"Generated: **{now}**\n")

    # 1) Executive summary
    lines.append("## 1. Executive Summary\n")
    lines.append(f"- Total strategies analyzed: **{total}**\n")
    for k, v in label_counts.items():
        lines.append(f"- {k}: **{v}**\n")

    lines.append("\nKey message: The system aligns strategies to actions using embeddings + Chroma, "
                 "and proposes improvements (rewrites + KPIs) using an LLM with evaluation loop.\n")

    # 2) Key findings
    lines.append("## 2. Key Findings\n")
    if len(weak_top) == 0:
        lines.append("- No strategies labeled Weak.\n")
    else:
        lines.append(f"- Lowest-alignment (Weak) strategies (top {min(top_n_weak,len(weak_top))}):\n")
        for _, r in weak_top.iterrows():
            sid = r.get("strategy_id", "")
            head = r.get("strategy_headline", "")
            best_a = r.get("best_action_id", "")
            best_b = r.get("best_boosted_similarity", 0.0)
            lines.append(f"  - **{sid}**: {head} → best action **{best_a}** (boosted={best_b:.3f})\n")

    # 3) Recommendations (LLM outputs)
    lines.append("\n## 3. Recommendations (LLM Strategy Improvement Generator)\n")
    if not improvements:
        lines.append("- No saved LLM improvements found yet. Generate suggestions in the dashboard first.\n")
    else:
        # show a few improvements
        shown = 0
        for sid, payload in improvements.items():
            sug0 = (payload.get("suggestions") or [{}])[0]
            ev = payload.get("evaluation") or {}
            proposed = sug0.get("proposed_text", "")
            kpis = sug0.get("kpis") or []
            citations = sug0.get("citations") or []

            lines.append(f"### {sid}\n")
            lines.append(f"- Issue: `{payload.get('issue','')}`\n")
            lines.append(f"- Cited action(s): {', '.join(citations) if citations else 'N/A'}\n")

            before_b = ev.get("before_boosted_similarity")
            after_b = ev.get("after_boosted_similarity", ev.get("best_after_boosted_similarity"))
            delta = ev.get("delta_boosted")

            if before_b is not None and after_b is not None:
                lines.append(f"- Alignment: before={before_b:.3f}, after={after_b:.3f}"
                             + (f", delta={delta:.3f}\n" if delta is not None else "\n"))

            lines.append("\n**Proposed improved strategy:**\n")
            lines.append(f"> {proposed}\n")

            if kpis:
                lines.append("\n**KPIs:**\n")
                for k in kpis:
                    lines.append(f"- {k.get('name','KPI')}: {k.get('metric','')} | "
                                 f"target={k.get('target','')} | timeframe={k.get('timeframe','')}\n")
            else:
                lines.append("\n- No KPI list provided.\n")

            lines.append("\n")
            shown += 1
            if shown >= 10:
                lines.append("_Showing first 10 improvements. See improvements_latest.json for full list._\n")
                break

    # 4) Knowledge graph summary
    lines.append("## 4. Knowledge Graph View (Strategy → Action → KPI)\n")
    lines.append("The dashboard visualizes Strategy → top Action(s) → KPI(s) generated by the LLM.\n")
    lines.append("For each improved strategy, KPI nodes are linked to the cited action(s) to preserve traceability.\n")

    # 5) Appendix: sample mappings table
    lines.append("\n## 5. Appendix: Sample Alignment Rows\n")
    sample = df.head(10)[["strategy_id","strategy_headline","label","best_action_id","best_boosted_similarity"]]
    def df_to_md_table(df):
        cols = list(df.columns)
        # header
        out = []
        out.append("| " + " | ".join(cols) + " |\n")
        out.append("| " + " | ".join(["---"] * len(cols)) + " |\n")
        # rows
        for _, r in df.iterrows():
            out.append("| " + " | ".join(str(r[c]).replace("\n", " ") for c in cols) + " |\n")
        return "".join(out)

    lines.append(df_to_md_table(sample))

    lines.append("\n")

    md = "".join(lines)

    if out_path is None:
        out_path = f"outputs/isps_report_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.md"
    Path(out_path).write_text(md, encoding="utf-8")
    return out_path
